trigger:
  branches:
    include:
      - main
      - development

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'app'
  appName: 'reactaflal'

stages:
  - stage: Build
    displayName: 'Build and Test'
    jobs:
      - job: Build
        displayName: 'Build'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'
          
          - script: npm install
            displayName: 'Install Dependencies'
          
          - script: npm run build
            displayName: 'Build React App'
            continueOnError: true  # Continue on error to run tests even if build fails

  - stage: Deploy_DEV
    displayName: 'Deploy to Development'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        displayName: 'Deploy'
        steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appName: $(appName)
              package: '$(System.DefaultWorkingDirectory)/build'
              appType: webApp
